# Patriarchs Category
level = "category"
id = "02"
title = "Patriarchs"
beg = 4
count = 5

[image]
filename = "00-01c.png"

# Stories in this category
[[stories]]
id = "04"
title = "God's Covenant with Abraham"

[[stories]]
id = "05"
title = "The Son of Promise"

[[stories]]
id = "06"
title = "God Provides for Isaac"

[[stories]]
id = "07"
title = "God Blesses Jacob"

[[stories]]
id = "08"
title = "God Saves Joseph and His Family"

